auctions/api/urls.py
from django.conf.urls import url

from .views import (
    auction_detail,
    item_list,
    item_detail,
    auction_list,
    auctioneer_detail,
    auctioneer_list,
    item_listing,
    auction_listing,
)

urlpatterns = [

    url(r'^auctioneers/$', auctioneer_list),
    url(r'^auctioneers/(?P<pk>[0-9]+)/$', auctioneer_detail),
    url(r'^auctions/$', auction_list),
    url(r'^auctions/(?P<pk>[0-9]+)/$', auction_detail),

    url(r'^auction_listing/(?P<auction_id>[0-9]+)/$', auction_listing),
    url(r'^item_listing/(?P<auction_id>[0-9]+)/$', item_listing),

    url(r'^items/$', item_list),
    url(r'^items/(?P<pk>[0-9]+)/$', item_detail),

]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from auctions import views
from auctions.api import urls as api_url
from tasks import urls as tasks_url
from django.conf import settings
from django.conf.urls.static import static


import debug_toolbar
urlpatterns = [

    url(r'^__debug__/', include(debug_toolbar.urls)),

    url(r'^auctioneer-registration-completed/$', views.AuctioneerRegistrationCompleted.as_view(), name='auctioneer_registration_completed'),
    url(r'^auctioneer-registration-form/$', views.AuctioneerRegistrationForm.as_view(), name='auctioneer_registration_form'),
    url(r'^bidder-registration-form/$', views.BidderRegistrationForm.as_view(), name='bidder_registration_form'),

    url(r'^auctions/inventory_import/(?P<auction_id>[0-9]+)/$', views.auction_item_import_csv, name='auction_item_import_csv'),
    url(r'^auctions/details/(?P<auction_id>[0-9]+)/$', views.catalog_auction_details, name='auction_details'),
    url(r'^auctions/$', views.catalog_auctions, name='auctions'),

    url(r'^categories/$', views.catalog_categories, name='categories'),
    url(r'^categories/(?P<item_category_slug>[\w\-_]+)/$', views.catalog_category_items, name='category_items'),

    url(r'^items/(?P<item_id>[0-9]+)/$', views.catalog_item_details, name='item'),
    url(r'^items/$', views.catalog_items, name='items'),

    url(r'^search/(?P<criteria>[\w\-_%20]+)', views.catalog_search, name='search'),

    url(r'^auctioneers/(?P<auctioneer_slug>[\w\-_]+)/auctions/(?P<auction_slug>[\w\-_]+)/items/(?P<item_slug>[\w\-_]+)/$', views.catalog_auctioneers_auctions_items_details, name='catalog_auctioneers_auctions_items_details'),
    url(r'^auctioneers/(?P<auctioneer_slug>[\w\-_]+)/auctions/(?P<auction_slug>[\w\-_]+)/items/$', views.catalog_auctioneers_auctions_items, name='catalog_auctioneers_auctions_items'),
    url(r'^auctioneers/(?P<auctioneer_slug>[\w\-_]+)/auctions/$', views.catalog_auctioneers_auctions, name='catalog_auctioneers_auctions'),
    url(r'^auctioneers/(?P<auctioneer_slug>[\w\-_]+)/details/$', views.catalog_auctioneers_details, name='catalog_auctioneers_details'),
    url(r'^auctioneers/', views.catalog_auctioneers, name='auctioneers'),

    url(r'^api/', include(api_url)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^tasks/', include(tasks_url, namespace='tasks')),

    url(r'^$', views.catalog_index, name='index'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from .views import (
    TasksListView,
    TasksDetailView,
)


urlpatterns = [

    url(r'^(?P<pk>[0-9]+)/$', TasksDetailView.as_view(), name='detail'),
    # url(r'^list/$', tasks_list),
    # url(r'^edit/(?P<pk>[0-9]+)/$', auctioneer_detail),
    # url(r'^add/$', auction_list),
    url(r'^$', TasksListView.as_view(), name='list'),

]

auctions/forms/item_csv_upload_form.py
from django import forms


class ItemCSVUploadForm(forms.Form):
    csv_file = forms.FileField()

auctions/api/views.py
# Create your views here.
from rest_framework import status
from rest_framework import permissions
from rest_framework.decorators import api_view, permission_classes
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from .serializers import(
    AuctionSerializer,
    ItemSerializer,
    ItemListingSerializer,
    AuctioneerSerializer,
    AuctionListingSerializer,
)
from auctions.models import(
    Auction,
    Auctioneer,
    Item,
)


@api_view(['GET', 'POST'])
@permission_classes((permissions.AllowAny,))
def auction_list(request, format=None):
    if request.method == 'GET':
        auction = Auction.objects.all()
        serializer = AuctionSerializer(auction, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = AuctionSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'PUT', 'DELETE'])
@permission_classes((permissions.AllowAny,))
def auction_detail(request, pk, format=None):

    try:
        auction = Auction.objects.get(pk=pk)
    except Auction.DoesNotExist:
        return Response(status=404)

    if request.method == 'GET':
        serializer = AuctionSerializer(auction)
        return Response(serializer.data)

    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = AuctionSerializer(auction, data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        auction.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(['GET', 'POST'])
@permission_classes((permissions.AllowAny,))
def auctioneer_list(request, format=None):
    if request.method == 'GET':
        auctioneer = Auctioneer.objects.all()
        serializer = AuctioneerSerializer(auctioneer, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = AuctioneerSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'PUT', 'DELETE'])
@permission_classes((permissions.AllowAny,))
def auctioneer_detail(request, pk, format=None):

    try:
        auctioneer = Auctioneer.objects.get(pk=pk)
    except Auctioneer.DoesNotExist:
        return Response(status=404)

    if request.method == 'GET':
        serializer = AuctioneerSerializer(auctioneer)
        return Response(serializer.data)

    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = AuctioneerSerializer(auctioneer, data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        auctioneer.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(['GET', 'POST'])
@permission_classes((permissions.AllowAny,))
def item_list(request, format=None):
    if request.method == 'GET':
        item = Item.objects.all()
        serializer = ItemSerializer(item, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = ItemSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'PUT', 'DELETE'])
@permission_classes((permissions.AllowAny,))
def item_detail(request, pk, format=None):

    try:
        item = Item.objects.get(pk=pk)
    except Item.DoesNotExist:
        return Response(status=404)

    if request.method == 'GET':
        serializer = ItemSerializer(item)
        return Response(serializer.data)

    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = ItemSerializer(item, data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        item.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(['GET'])
@permission_classes((permissions.AllowAny,))
def item_listing(request, auction_id):
    if request.method == 'GET':
        auction = Auction.objects.get(id=auction_id)
        serializer = ItemListingSerializer({"auction": auction})
        return Response(serializer.data)


@api_view(['GET'])
@permission_classes((permissions.AllowAny,))
def auction_listing(request, auction_id):
    if request.method == 'GET':
        auction = Auction.objects.get(id=auction_id)
        serializer = AuctionListingSerializer({"auction": auction})
        return Response(serializer.data)

auctions/views.py
import codecs
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, authenticate
from django.views.generic import View
from .forms import AuctioneerRegistration, BidderRegistration, ItemCSVUploadForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.admin.views.decorators import staff_member_required
import io


from auctions.models import (
    Auction,
    Auctioneer,
    Item,
    ItemCategory
)


@staff_member_required
def auction_item_import_csv(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)
    if request.method == 'POST':
        form = ItemCSVUploadForm(request.POST, request.FILES)
        if form.is_valid():
            file = io.StringIO(request.FILES['csv_file'].read().decode('utf-8'))
            auction.import_item_csv(file)
            return redirect('index')
    else:
        form = ItemCSVUploadForm()

    context = {
        'form': form,
    }
    return render(request, 'auction_item_import_csv_form.html', context)


def catalog_index(request):
    context = {
        'show_carousel': True,
    }
    return render(request, 'index.html', context)


def catalog_auctions(request):
    auctions = Auction.objects.all()
    context = {
        'auctions': auctions,
    }
    return render(request, 'auctions.html', context)


def catalog_auction_details(request, auction_id):
    auctions = Item.objects.all()
    context = {
        'auctions': auctions,
    }
    return render(request, 'auction_details.html', context)


def catalog_auctioneers(request):
    auctioneers = Auctioneer.objects.filter(activated=True).order_by('name')
    context = {
        'auctioneers': auctioneers,
    }
    return render(request, 'auctioneers.html', context)


def catalog_auctioneers_details(request, auctioneer_slug):
    auctioneer = get_object_or_404(Auctioneer, slug=auctioneer_slug)
    context = {
        'auctioneer': auctioneer,
    }
    return render(request, 'auctioneer_details.html', context)


def catalog_auctioneers_auctions(request, auctioneer_slug):
    auctioneer = get_object_or_404(Auctioneer, slug=auctioneer_slug)
    auctions = auctioneer.auctions.all()
    context = {
        'auctioneer': auctioneer,
        'auctions': auctions,
    }
    return render(request, 'auctioneer_auctions.html', context)


def catalog_auctioneers_auctions_items(request, auctioneer_slug, auction_slug):
    auctioneer = get_object_or_404(Auctioneer, slug=auctioneer_slug)
    auction = get_object_or_404(Auction, slug=auction_slug)
    items_list = Item.objects.filter(auction_id=auction.id)
    item_categories = ItemCategory.objects.all().order_by('name')

    paginator = Paginator(items_list, 3)
    page = request.GET.get('page')

    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    context = {
        'auctioneer': auctioneer,
        'auction': auction,
        'items': items,
        'item_categories': item_categories,
    }
    return render(request, 'auction_items.html', context)


def catalog_auctioneers_auctions_items_details(request, auctioneer_slug, auction_slug, item_slug):
    auctioneer = get_object_or_404(Auctioneer, slug=auctioneer_slug)
    auction = auctioneer.auctions.filter(slug=auction_slug)
    item = get_object_or_404(Item, slug=item_slug)
    item_categories = ItemCategory.objects.all().order_by('name')
    context = {
        'auctioneer': auctioneer,
        'auction': auction,
        'item': item,
        'item_categories': item_categories,
    }
    return render(request, 'item_details.html', context)


def catalog_categories(request):
    item_categories = ItemCategory.objects.all().order_by('name')
    context = {
        'item_categories': item_categories,
    }
    return render(request, 'categories.html', context)


def catalog_item_details(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }
    return render(request, 'item_details.html', context)


def catalog_items(request):
    items_list = Item.objects.filter(published=True).order_by('run').order_by('lot').order_by('name')

    paginator = Paginator(items_list, 3)
    page = request.GET.get('page')

    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    context = {
        'items': items,
    }
    return render(request, 'items.html', context)


def catalog_search(request, criteria):
    items = Item.objects.filter(name__contains=criteria)
    context = {
        'items': items
    }
    return render(request, 'search.html', context)


def catalog_auction_items(request, auction_id, item_id):
    items = Item.objects.all()
    context = {
        'items': items,
    }
    return render(request, 'items.html', context)


class AuctioneerRegistrationForm(View):
    form_class = AuctioneerRegistration
    template_name = 'auctioneer_registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            auctioneer = form.save(commit=False)
            auctioneer.name = form.cleaned_data.get('name')

            try:
                auctioneer.save()
            except Exception as e:
                return render(request, self.template_name, {'form': form, 'error': 'Email Already in Use.'})

            return redirect('AuctioneerRegistrationCompleted')

        return render(request, self.template_name, {'form': form, 'error': 'Please fill this form.'})


class AuctioneerRegistrationCompleted(View):
    template_name = 'auctioneer_registration_completed.html'

    def get(self, request):
        return render(request, self.template_name)


class BidderRegistrationForm(View):
    form_class = BidderRegistration
    template_name = 'bidder_registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get('password')
            email = form.cleaned_data.get('email')

            # try:
            #     validate_email(email)
            #     valid_email = True
            # except validate_email.ValidationError:
            #     valid_email = False
            #
            # if not valid_email:
            #     return render(request, self.template_name, {'form': form, 'error': 'Invalid email address.'})

            user.username = email
            user.set_password(password)

            try:
                user.save()
            except Exception as e:
                return render(request, self.template_name, {'form': form, 'error': 'Email Already in Use.'})

            user = authenticate(username=email, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('index')

        return render(request, self.template_name, {'form': form, 'Error': 'please fill this form.'})


# class BidderRegistrationForm(View):


def catalog_category_items(request, item_category_slug):
    item_category = get_object_or_404(ItemCategory, slug=item_category_slug)
    items_list = Item.objects.filter(published=True).filter(item_categories__slug=item_category_slug).order_by('run').order_by('lot').order_by('name')

    paginator = Paginator(items_list, 3)
    page = request.GET.get('page')

    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    context = {
        'item_category': item_category,
        'items': items,
    }
    return render(request, 'category_items.html', context)

auctions/templates/auction_item_import_csv_form.html
{% extends 'base.html' %}

{% block title %}Inventory Import{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid" id="jumbotron-become-a-bidder">
        <div class="container">
            <h1 class="display-3">Become an Auctioneer</h1>

            <p class="lead">Auctioneers can sell items on this website.</p>
        </div>
    </div>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-header card-inverse" style="background-color: #333; border-color: #333;">
                    Auctioneer Registration Details
                </div>
                <div class="card-block">
                    <p>Auctioneers can sell items on this website.</p>
                </div>
            </div>
        </div>
        <div class="col-8">

            {% if error %}
                <div class="alert alert-danger" role="alert">
                    <strong>Error!</strong> {{ error }}.
                </div>
            {% endif %}

            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <div class="card">
                    <div class="card-header card-inverse" style="background-color: #333; border-color: #333;">
                        Auctioneer Information
                    </div>
                    <div class="card-block">
                        <div class="form-group">
{#                            <label for="{{ form.name.id_for_label }}">Name:</label>#}
{#                            {{ form.name }}#}
{#                            <input type="text" class="form-control" name="name" id="name" placeholder="Name" required>#}
                        </div>
                        {% if form.name.errors %}
                            <div class="alert alert-danger" role="alert">{{ form.name.errors }}</div>
                        {% endif %}
                    </div>
                </div>

                <br>

                <input type="submit" class="btn btn-primary" value="Register">
            </form>
        </div>
    </div>
    <br>
{% endblock %}

auctions/templates/auction_items.html
{% extends 'base.html' %}

{% block title %}Items{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-3">{{ auction.name }}</h1>
            <p class="lead">Feel free to browse the list of available items</p>
        </div>
    </div>
{% endblock %}

{% block content %}

    <p><a href="/auctioneers/{{ auctioneer.slug }}/details/">Auctioneer Details</a></p>
    <p><a href="/auctions/{{ auction.slug }}/details/">Auction Details</a></p>

    <div id="accordion" role="tablist" aria-multiselectable="true">
      <div class="card">
        <div class="card-header" role="tab" id="headingOne">
          <h5 class="mb-0">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Auction Information
            </a>
          </h5>
        </div>

        <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
          <div class="card-block">
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" role="tab" id="headingTwo">
          <h5 class="mb-0">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Auctioneer information
            </a>
          </h5>
        </div>
        <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
          <div class="card-block">
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
          </div>
        </div>
      </div>
    </div>

    <br>

    {% include 'includes/items.html' with items=items %}


{% endblock %}

auctions/templates/auctioneer_auctions.html
{% extends 'base.html' %}

{% block title %}{{ auctioneer.name }}{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-3">{{ auctioneer.name }}</h1>
            <p class="lead"></p>
        </div>
    </div>
{% endblock %}

{% block content %}

    Auctions {{ auctions|length }} <br>

    <ul>
    {% for auction in auctions %}
    <li>
        {{ auction.name }} |
        <a href="/auctioneers/{{ auctioneer.slug }}/auctions/{{ auction.slug }}/details/">Auction Details</a>  |
        <a href="/auctioneers/{{ auctioneer.slug }}/auctions/{{ auction.slug }}/items/">Items Listing</a> |
        <a href="/auctioneers/{{ auctioneer.slug }}/details/">Auctioneer Details</a>
    </li>
    {% endfor %}
    </ul>

{% endblock %}

auctions/templates/auctioneer_details.html
{% extends 'base.html' %}

{% block title %}{{ auctioneer.name }}{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-3">{{ auctioneer.name }}</h1>

            <p class="lead">{% if auctioneer.motto %}{{ auctioneer.motto|title }}{% else %}&nbsp;{% endif %}</p>
        </div>
    </div>
{% endblock %}

{% block content %}

    {% if auctioneer.auctioneer_address.count > 0 %}
        {% include 'includes/google_map.html' with address=auctioneer.auctioneer_address.all info=auctioneer.name %}
    {% endif %}

{% endblock %}

auctions/templates/auctioneer_registration_completed.html
{% extends 'base.html' %}

{% block title %}Auctioneer registration completed{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid" id="jumbotron-become-a-bidder">
        <div class="container">
            <h1 class="display-3">Auctioneer registration completed</h1>
            <p class="lead">asys will contact you within 48 hours</p>
        </div>
    </div>
{% endblock %}

{% block content %}

{% endblock %}

auctions/templates/auctioneer_registration_form.html
{% extends 'base.html' %}

{% block title %}Become a bidder{% endblock %}

{% block jumbotron %}
    <div class="jumbotron jumbotron-fluid" id="jumbotron-become-a-bidder">
        <div class="container">
            <h1 class="display-3">Become an Auctioneer</h1>

            <p class="lead">Auctioneers can sell items on this website.</p>
        </div>
    </div>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-header card-inverse" style="background-color: #333; border-color: #333;">
                    Auctioneer Registration Details
                </div>
                <div class="card-block">
                    <p>Auctioneers can sell items on this website.</p>
                </div>
            </div>
        </div>
        <div class="col-8">

            {% if error %}
                <div class="alert alert-danger" role="alert">
                    <strong>Error!</strong> {{ error }}.
                </div>
            {% endif %}

            <form action="" method="post">
                {% csrf_token %}
                {{ form }}
                <div class="card">
                    <div class="card-header card-inverse" style="background-color: #333; border-color: #333;">
                        Auctioneer Information
                    </div>
                    <div class="card-block">
                        <div class="form-group">
{#                            <label for="{{ form.name.id_for_label }}">Name:</label>#}
{#                            {{ form.name }}#}
{#                            <input type="text" class="form-control" name="name" id="name" placeholder="Name" required>#}
                        </div>
                        {% if form.name.errors %}
                            <div class="alert alert-danger" role="alert">{{ form.name.errors }}</div>
                        {% endif %}
                    </div>
                </div>

                <br>

                <input type="submit" class="btn btn-primary" value="Register">
            </form>
        </div>
    </div>
    <br>
{% endblock %}

auctions/templates/footer.html
<div style="background-color: #222; border-color: #222;">
    <br>

    <div class="container">
        <div class="row">
            <div class="col-6 col-md-4 text-white">Copyright</div>
            <div class="col-6 col-md-4 text-white text-center">
                <h3>asys</h3>
                <br>
                Site map <br>
            </div>
            <div class="col-6 col-md-4 text-white text-right">
                <h3>Autioneers</h3>
                <br>
                <a href="/admin/" class="btn btn-primary">Auctioneer Login</a> <br>
                <br>
                <a href="/auctioneer-registration-form/" class="btn btn-success">Auctioneer Sign Up</a> <br>
            </div>
        </div>
    </div>
    <br>
    <br>
</div>

auctions/templates/nav.html
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">ASYSTEM</a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/auctioneers/">Auctioneers</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/auctions/">Auctions</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/items/">Items</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/categories/">Categories</a>
            </li>
            {% if user.is_staff %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'tasks:list' %}">Tasks</a>
                </li>
            {% endif %}
            <!--
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
              <div class="dropdown-menu" aria-labelledby="dropdown01">
                <a class="dropdown-item" href="#">Auctions</a>
                <a class="dropdown-item" href="#">Items</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>-->
        </ul>

        <form class="form-inline" action="/search/" method="get">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" name="criteria" id="criteria">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="searchBtn">Search</button>
        </form>

        <script>
            function post_form() {
                var nameValue = document.getElementById("criteria").value;
                location.assign("/search/" + nameValue + "/");
            }
            myBtn = document.getElementById("searchBtn");
            myBtn.onclick = function () {
                post_form();
                return false;
            }
        </script>

        <ul class="nav justify-content-end">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/admin/">{{ user.first_name }}</a>
                </li>
            {% else %}
                <li class="nav-item active" style="padding:0 10px">
                    <a class="nav-link btn btn-success" href="/bidder-registration-form/">Become a bidder</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link btn btn-primary" href="/admin/">Bidder login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>